# Firebird configuration file for Firebird 3.0 64-bit SuperServer
# Optimized by IBSurgeon (www.ib-aid.com) for HQbird distribution.
#
# This is an optimized configuration for Firebird 3.0 SuperServer 64 bit, it can be used
# instead of standard firebird.conf from 3.0 distribution - copy it to Firebird folder,
# rename it to firebird.conf, then restart Firebird 
# (all users should be disconnected before restart!). Keep old config as a backup!
# Please be aware that some settings can be configured at database level (in databases.conf)
#
# If you need configuration file, optimized for your specific environment 
# to get the best possible performance, or if your performance problem 
# still persists after configuration changes, contact us:
# http://www.ibsurgeon.com/en/firebird-interbase-performance-optimization-service/
# or via email support@ib-aid.com

# Make sure you have HQBird plugins (fbtrace2db and replconf) in plugins folder of Firebird
#

#ServerMode = Super

#DatabaseAccess = Full
#RemoteAccess = true
#ExternalFileAccess = None
#UdfAccess = Restrict UDF
#TempDirectories =
#AuditTraceConfigFile =
#MaxUserTraceLogSize = 10

DefaultDbCachePages = 50000

#DatabaseGrowthIncrement = 128M
#FileSystemCacheThreshold = 64K
#FileSystemCacheSize = 0
#RemoteFileOpenAbility = 0

TempBlockSize = 2M
TempCacheLimit = 364M

# AuthServer and AuthClient determine what authentication methods will be used
# by network server and client redirector. Secure remote passwords plugin
# is default one. Except configured by default SRP plugin firebird also has
# Legacy_Auth plugin which is used to emulate pre-FB3 login protocol making it
# possible for client to talk to old servers and for server to listen to requests
# from old clients. Legacy_Auth is VERY unsecure. On windows Win_Sspi plugin may
# be also used - it implements windows trusted authentication and backward
# compatible with 2.1 and 2.5 clients and servers running on windows.
# Per-database configurable.

AuthServer = Srp, Legacy_Auth

# Cambiamos a la linea de abajo el 07.09.2021 porque al crear usuarios
# nos estaba dando errores de plugin
# Error loading plugin Legacy_Auth.
# Module /opt/firebird/plugins/Legacy_Auth does not contain plugin Legacy_Auth type 5.
#UserManager = Legacy_Auth, Srp

UserManager = Srp, Legacy_UserManager

#hqbird traceapi plugin should be in plugins folder!
TracePlugin = fbtrace2db

#CryptPlugin = Arc4
#KeyHolderPlugin =
#Providers = Remote,Engine12,Loopback
#DeadlockTimeout = 10
#MaxUnflushedWrites = 100
#MaxUnflushedWriteTime = 5
#BugcheckAbort = 0
#RelaxedAliasChecking = 0
#ConnectionTimeout = 180
#(for client) / Required (for server)

WireCrypt = Disabled 
#DummyPacketInterval = 0
#RemoteServiceName = gds_db

RemoteServicePort = 3050

#RemoteAuxPort = 0
#TcpRemoteBufferSize = 8192
#TcpNoNagle = 1
#RemoteBindAddress =

LockMemSize = 9M

#LockAcquireSpins = 0

LockHashSlots = 30011

#EventMemSize = 64K
#CpuAffinityMask = 0
#GCPolicy = combined
#SecurityDatabase = $(dir_secDb)/security3.fdb

GuardianOption = 1

#ProcessPriorityLevel = 0
#IpcName = FIREBIRD
#RemotePipeName = interbas